# Starter pipeline
trigger:
- main

pool:
  name: default

jobs:
- job: Build
  steps:
  - task: S3Upload@1
    inputs:
      awsCredentials: 'demo'
      regionName: 'ap-southeast-1'
      bucketName: 'mybucket3396'
      globExpressions: '**'
